name: My First Workflow

on: 
  push:
    branches: 
      - main

jobs:
  first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: |
          echo "Hello, World! From ${{ github.actor }}"
          echo "Current branch: ${{ github.ref }}"
        
