name: My First Workflow

on: 
  push:
    branches: 
      - main

jobs:
  first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        env:
          GREETER_NAME: ${{ vars.GREETER_NAME || 'Default Greeter' }}
          WHO_TO_GREET: ${{ secrets.WHO_TO_GREET || 'World' }}
        run: |
          echo "Hello, ${WHO_TO_GREET} From ${{ github.actor }}"
          echo "Current branch: ${{ github.ref }}"
          echo "My name is ${GREETER_NAME}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files using tree
        run: |
          sudo apt-get update
          sudo apt-get install tree
          tree -L 2
